project:
  type: website
  output-dir: docs

website:
  title: "Isabella Munhoz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd # add your posts.qmd file to your navbar!

format:
  html:
    theme: lux
    css: styles.css
    toc: true



