project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Isabella Munhoz" # título no menu preto superior
  navbar: # menu preto superior
    left:
      - href: index.qmd # para qual página será redirecionado quando clicado
        text: Home # nome que aparece no menu preto superior
      - href: posts.qmd
        text: Posts
      - href: about.qmd
        text: About

format:
  html:
    theme: lux
    css: styles.css