project:
  type: website
  output-dir: docs

website:
  title: "Isabella Munhoz"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - posts.qmd # add your posts.qmd file to your navbar!
      - about.qmd
      
format:
  html:
    theme: lux
    css: styles.css